[package]
name = "rust-template-project"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.131", features = ["derive"] }
toml = "0.5.8"
anyhow = "1.0.51"

[[bin]]
bench = false
path = "src/main.rs"
name = "rust-template-project"
